"""empty message

Revision ID: 747f88337186
Revises: ad2b9d0dbc42
Create Date: 2023-12-20 13:27:31.717882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '747f88337186'
down_revision = 'ad2b9d0dbc42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userConversation_table', schema=None) as batch_op:
        batch_op.alter_column('unread',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userConversation_table', schema=None) as batch_op:
        batch_op.alter_column('unread',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
